OnlineMovieTicketManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import Homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('myadmin/',include('myadmin.urls')),
    path('',Homepage),
]

myadmin/urls.py
from django.urls import path
from .views import *

app_name='myadmin'

urlpatterns = [
    path('login/',Myadminlogin,name='login'),
    path('dashboard/',Dashboard),
    path('logout/',LogoutAdmin,name='logout'),
]

user/urls.py
from django.urls import path
from .views import *

app_name="user"

urlpatterns = [
    path('login/',LoginUser,name='login'),
    path('dashboard/',Dashboard),
    path('logout/',LogoutUser,name='logout'),
    path('registration/',Registration,name='registration'),
    path('movies/',Moveplace,name='movies'),
    path('movies/<int:pk>/<slug:place>/',Moviename,name='movieplace'),
    path('movies/<int:pk>/<slug:place>/<str:moviename>/<slug:language>/',Movieticket,name='movieticket'),
    
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

class MyUser(models.Model):
    myuser=models.OneToOneField(User,on_delete=models.CASCADE)
    type = models.CharField(max_length=10, default="user")
    
    def __str__(self):
        return "{0}({1})".format(self.myuser.username,self.type)


class MovieTheater(models.Model):
    theatername=models.CharField(max_length=60)
    theaterplace=models.CharField(max_length=20)

    def __str__(self):
        return "{0}({1})".format(self.theatername,self.theaterplace)
    
class MovieName(models.Model):
    theater=models.ForeignKey(MovieTheater, on_delete=models.CASCADE)
    moviename=models.CharField(max_length=50)
    language=models.CharField(max_length=10,default="Hindi")
    totaltickets=models.IntegerField(default=120)
    availabletickets=models.IntegerField(default=0)
    ticketprice=models.IntegerField(default=100)
    
    def __str__(self):
        return "{0}({1}-{2})".format(self.moviename,self.theater.theatername,self.theater.theaterplace)
    

class MovieTicket(models.Model):
    ticketuser=models.OneToOneField(MyUser,on_delete=models.CASCADE)
    moviename=models.OneToOneField(MovieName,on_delete=models.CASCADE)
    moviedate=models.DateField()
    movietime=models.TimeField()
    bookingtime=models.DateTimeField(default=datetime.datetime.now())
    quantity=models.IntegerField()
    totalprice=models.IntegerField()

    def __str__(self):
        return "{0}({1}-{2})".format(self.moviename.moviename,self.ticketuser.myuser.username,self.moviedate)
    
    

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from random import choice

class RegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Optional'}
    ), required=False)

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Optional'}
    ), required=False)

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}
    ))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}
    ))
    password2 = forms.CharField(label='Confirmed Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}
    ))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email',
                  'password1', 'password2']
        

user/views.py
from django.shortcuts import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import *
from .models import *
from .forms import *
from django.db.models import Q
from django.template.context_processors import request
from django.contrib.auth.decorators import login_required

# Create your views here.
def LoginUser(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            user_type=[i.myuser.username for i in MyUser.objects.all()]
            if user:
                if user.username in user_type:
                    auth.login(request, user)
                    return HttpResponseRedirect("/user/dashboard/")
                else:
                    messages.error(request, '✘ You are Admin User Please Login via ', extra_tags='safe')
                    return HttpResponseRedirect('/user/login/')
            else:
                messages.error(request, '✘ Incorrect Username and Password!')
                return HttpResponseRedirect('/user/login/')
        else:
            form = AuthenticationForm()
            return render(request, 'user/login.html', {'form': form})
    else:
        return HttpResponseRedirect('/user/dashboard/')
    
    
@login_required(login_url="/user/login/")
def Dashboard(request):
    return render(request,"user/dashboard.html")


def LogoutUser(request):
    auth.logout(request)
    return HttpResponseRedirect('/user/login/')


def Registration(request):
    if request.method=="POST":
        form=RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            myusr=User.objects.get(username=request.POST['username'])
            MyUser.objects.create(myuser=myusr)
            messages.success(request, 'You Account Registered Successfully!')
            return HttpResponseRedirect('/user/login/')
    else:
        form=RegistrationForm()
    return render(request, 'user/registration.html', {'form': form})


def Homepage(request):
    return render(request, 'user/homepage.html') 


@login_required(login_url="/user/login/")
def Moveplace(request):
    if request.method=="POST":
        value=request.POST['placen']
        obj=MovieTheater.objects.filter(Q(theaterplace__icontains=value[0:3]))
        if obj:
            return render(request, 'user/movieplace.html',{'obj':obj})
        else: 
            return render(request, 'user/movieplace.html')
    else:
        return render(request, 'user/movieplace.html') 


@login_required(login_url="/user/login/")
def Moviename(request,pk,place):
    theater_obj=MovieTheater.objects.filter(id=pk)
    mylist=[]
    for i in theater_obj:
        theater_name=i.theatername
    
    obj=MovieName.objects.all()
    for i in obj:
        if i.theater.theatername == theater_name:
            image_name="images/{}.jpg".format(i.moviename)
            mylist.append((i.moviename,image_name,i.language))
    
    return render(request, 'user/moviename.html',{'mylist':mylist,"pk":pk,"place":place}) 


def Movieticket(request,pk,place,moviename,language):
    username="vinay"
    for i in MyUser.objects.all():
        if i.myuser.username==username:
            Tmyuser=i
    print(Tmyuser)
    theater=MovieTheater.objects.get(id=pk)
    for i in MovieName.objects.filter(moviename=moviename,language=language,theater=theater):
        Tmoviename=i
    print(Tmoviename)
    Tdate="2018-05-09"
    Ttime="19:34:42"

    return render(request, 'user/movieticket.html')
    










user/templates/user/dashboard.html
<h1>Welcome,{{ request.user }}</h1>
<br><br><br><br>
<a href="{% url 'user:logout' %}"><h3>Logout<h3></a>
<br>
<a href="{% url 'user:movies' %}"><h3>Movies</h3></a>

user/templates/user/homepage.html
<h1>----------------------------------------HOMEPAGE-------------------------------------------<h1>

<br>
<a href="{% url 'user:login' %}"><h3>User Login</h3></a>
<a href="{% url 'myadmin:login' %}"><h3>Admin Login</h3></a>
<a href="{% url 'user:registration' %}"><h3>Registration</h3></a>

user/templates/user/login.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

{% if messages %}
    {% for message in messages %}
    	{% if 'safe' in message.tags %}
    		<div class="alert alert-danger container" > {{ message }}<a href="{% url "myadmin:login" %}">AdminLogin</a></div>
    	{% elif 'success' in message.tags  %}
    		<div class="alert alert-success container" > {{ message }}</div>
    	{% else  %}
        	<div class="alert alert-danger container" > {{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
      <div align="center" class="jumbotron">
      {{ form.as_p }}
      <button class="btn btn-success" type="submit">Login</button>
      <br> <br>
      <a href="{% url "user:registration" %}">Not Yet Register?</a>
       </div>
</form>

user/templates/user/moviename.html
{% load staticfiles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<br>
<div class="container">
	<div class="row">
	{% if mylist %}
		{% for i,j,k in mylist %}
				<div class="col-md-3">
					<img src="{% static j %}">
					<font size="4" color="light blue"><i>{{ i }}</i></font>
					<br>
					<p><font size="2" color="green	"><i>({{ k }})</i></font></p>
					 <button type="button" class="btn btn-warning" style="padding-left: 90px;padding-right: 90px;margin-bottom: 30px;"
					 onclick="location.href = '{% url "user:movieticket" pk=pk place=place moviename=i language=k %}';">BOOK</button>
				</div>
		{% endfor %}
		
	{% else %}
		<h1>No Movie Now Available. Please Wait For Update...</h1>
	
	{% endif %}
	</div>
</div>

user/templates/user/movieplace.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

<div align="center" class="jumbotron">
	<form method="post">
	 {% csrf_token %}
	   <div class="col-md-4" style="text-align: left">
	      <input class="form-control" type="text" name="placen" list="placename"/>
			<datalist id="placename">
			    <option value="Ulhasnagar">ULH</option>
			    <option value="Kalyan">KYN</option>
			    <option value="Thane">TH</option>
			</datalist>
			<br>
			<div align="center"><button class="btn btn-success" style="padding-left: 50px;padding-right: 50px;">Go</button></div>
	   </div>
	</form>
</div>


{% if obj %}
	{% for i in obj %}
	    <a href="{% url "user:movieplace" place=i.theaterplace pk=i.id %}"><h2>{{ i.theatername }}({{ i.theaterplace }})</h2></a>
	    
    	<br>
	{% endfor %}
	
{% else %}
	<h2>Match Not Found!!!</h2>
{% endif %}

user/templates/user/movietheater.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

<div align="center" class="jumbotron">
	<form method="post">
	 {% csrf_token %}
	   <div class="col-md-4" style="text-align: left">
	      <input type="text" name="placen" list="placename"/>
			<datalist id="placename">
			    <option value="Ulhasnagar">ULH</option>
			    <option value="Kalyan">KYN</option>
			    <option value="Mumbai">MUM</option>
			</datalist>
			<button class="btn btn-success">Go</button>
	   </div>
	</form>
</div>


{% if obj %}
	{% for i in obj %}
	    <a href="{% url "user:moviename" pk=i.id %}"><h2>{{ i.theatername }}</h2></a>
	    
    	<br>
	{% endfor %}
	
{% else %}
	<h2>Match Not Found!!!</h2>
{% endif %}

user/templates/user/movieticket.html
heloooooooooo ticket

user/templates/user/registration.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

<div align="center" class="jumbotron">
	<form method="post">
	 {% csrf_token %}
	   <div class="col-md-4" style="text-align: left">
	      {{ form.as_p }}
	   </div>
	   <button class="btn btn-success">Register</button>
	</form>
</div>
