OnlineMovieTicketManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import Homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('myadmin/',include('myadmin.urls')),
    path('',Homepage),
]

myadmin/urls.py
from django.urls import path
from .views import *

app_name='myadmin'

urlpatterns = [
    path('login/',Myadminlogin,name='login'),
    path('dashboard/',Dashboard),
    path('logout/',LogoutAdmin,name='logout'),
]

user/urls.py
from django.urls import path
from .views import *

app_name="user"

urlpatterns = [
    path('login/',LoginUser,name='login'),
    path('dashboard/',Dashboard),
    path('logout/',LogoutUser,name='logout'),
    path('registration/',Registration,name='registration'),
    path('movies/',Moveplace,name='movies'),
    path('movies/<int:pk>/<slug:place>/',Moviename,name='movieplace'),
    path('movies/<int:pk>/<slug:place>/<str:moviename>/<slug:language>/',Movieticket,name='movieticket'),
    
]

myadmin/models.py
from django.db import models

# Create your models here.

myadmin/views.py
from django.shortcuts import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import *
from user.models import MyUser

# Create your views here.

def Myadminlogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        user_type=[i.myuser.username for i in MyUser.objects.all()]
        if user:
            if user.username not in user_type:
                auth.login(request, user)
                return HttpResponseRedirect("/myadmin/dashboard/")
            else:
                messages.error(request, '✘ You are Not Authorized Permission To AdminLogin. Please Login Via ', extra_tags='safe')
                return HttpResponseRedirect('/myadmin/login/')
        else:
            messages.error(request, '✘ Incorrect Username and Password!')
            return HttpResponseRedirect('/myadmin/login/')
    else:
        form = AuthenticationForm()
        return render(request, 'myadmin/login.html', {'form': form})

   
def Dashboard(request):
    return render(request,"myadmin/dashboard.html")

def LogoutAdmin(request):
    auth.logout(request)
    return HttpResponseRedirect('/myadmin/login/')

myadmin/templates/myadmin/dashboard.html
<h1>Welcome,{{ request.user }}</h1>
<br><br><br><br>
<a href="{% url 'myadmin:logout' %}">Logout</a>

myadmin/templates/myadmin/login.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

{% if messages %}
    {% for message in messages %}
    	{% if 'safe' in message.tags %}
    		<div class="alert alert-danger container" > {{ message }}<a href="{% url "user:login" %}">UserLogin</a></div>
    	{% else %}
        	<div class="alert alert-danger container" > {{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
      <div align="center" class="jumbotron">
      {{ form.as_p }}
      <button class="btn btn-success" type="submit">Login</button>
       </div>
</form>